
const PREVIEWS = [
  "https://media1.tenor.com/m/dzxz-tZ1k20AAAAC/league-of-legends-patrick-bateman.gif",
  "https://media1.tenor.com/m/2YxH0ohuP24AAAAC/concert-alan-walker.gif",
  "https://media1.tenor.com/m/IOn_B2jrwAIAAAAC/panos-panay-panos.gif",
  "https://media1.tenor.com/m/MrNpsAD2umsAAAAC/alex-pereira-alex-poatan-pereira.gif",
  "https://media1.tenor.com/m/WdbDJiQLdjcAAAAC/valorant-roulette.gif",
  "https://media1.tenor.com/m/6xcG9ltNkaAAAAAC/singing-billie-eilish.gif",
  "https://media1.tenor.com/m/a30yTgSpqdQAAAAC/artemis-nasa.gif",
  "https://media1.tenor.com/m/PLraj9qNhGcAAAAC/bgalif.gif",
  "https://media1.tenor.com/m/j16fg2yvUC0AAAAd/basketball-basket.gif",
  "https://media1.tenor.com/m/Uq2gNyMTCooAAAAC/overwatch-ow2.gif",
  "https://media1.tenor.com/m/3HtC6h-wD54AAAAd/mars4-mars.gif",
  "https://media1.tenor.com/m/rEnG3oO9zBgAAAAd/dua-lipa-dua-lipa-roar.gif",
  "https://media1.tenor.com/m/t7142GghO4YAAAAC/web-summit-web-summit2019.gif",
  "https://media1.tenor.com/m/KdeAQr6ZdfYAAAAd/sofia-kenin-serve.gif",
  "https://media1.tenor.com/m/w_oNgQEEx2UAAAAd/moistcr1tikal-io.gif"
];



export const events = [
  {
    id: "1",
    title: "World Championship Finals – League of Legends",
    thumbnail: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&q=80",
    previewVideo: PREVIEWS[0],
    youtubeId: "ADaZLxI3uWg",
    category: "Gaming",
    date: "2026-04-15",
    time: "6:00 PM EST",
    views: 248000,
    description: "The biggest esports showdown of the year. The top 16 teams from around the globe clash in an epic five-game series to claim the Summoner's Cup. Watch world-class mechanics, jaw-dropping teamfights, and heart-pounding clutch plays unfold live.",
  },
  {
    id: "2",
    title: "Coachella Valley Music & Arts Festival – Main Stage",
    thumbnail: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80",
    previewVideo: PREVIEWS[1],
    youtubeId: "2NA7XUw51oo",
    category: "Music",
    date: "2026-04-19",
    time: "8:00 PM PST",
    views: 520000,
    description: "Stream the iconic Coachella Main Stage headliners from the comfort of your home. This year features genre-defying performances, immersive visuals, and surprise guest appearances. A cultural moment you cannot miss.",
  },
  {
    id: "3",
    title: "Google I/O 2026 – Keynote & Live Demos",
    thumbnail: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=800&q=80",
    previewVideo: PREVIEWS[2],
    youtubeId: "M7lc1UVf-VE",
    category: "Tech",
    date: "2026-04-22",
    time: "10:00 AM PDT",
    views: 189000,
    description: "Join Google engineers and executives as they unveil the next generation of AI, Android, and cloud technologies. Live coding demos, product launches, and deep-dives into the future of software development.",
  },
  {
    id: "4",
    title: "UFC 310 – Night of Champions",
    thumbnail: "https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=800&q=80",
    previewVideo: PREVIEWS[3],
    youtubeId: "_-dxHXd9B2Y",
    category: "Sports",
    date: "2026-04-26",
    time: "7:00 PM EST",
    views: 315000,
    description: "Five title fights. One legendary night. Watch the world's greatest mixed martial artists put their belts on the line inside the iconic Octagon. Stream the full card including prelims and main event live.",
  },
  {
    id: "5",
    title: "Valorant Champions Tour – EMEA Regional",
    thumbnail: "https://images.unsplash.com/photo-1560253023-3ec5d502959f?w=800&q=80",
    previewVideo: PREVIEWS[4],
    youtubeId: "wjVzNV0ezG0",
    category: "Gaming",
    date: "2026-04-28",
    time: "2:00 PM CET",
    views: 134000,
    description: "The EMEA powerhouses face off in the regional qualifier for the Valorant Champions Tour. Expert analysis, player cams, and real-time stats powered by the official Riot Games data feed.",
  },
  {
    id: "6",
    title: "Billie Eilish – Happier Than Ever World Tour Live",
    thumbnail: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80",
    previewVideo: PREVIEWS[5],
    youtubeId: "DyDfgMOUjCI",
    category: "Music",
    date: "2026-05-02",
    time: "9:00 PM GMT",
    views: 410000,
    description: "Billie Eilish brings her sold-out arena tour to screens worldwide. Cinematic stage production, intimate acoustic sets, and never-before-heard tracks performed for the first time live.",
  },
  {
    id: "7",
    title: "NASA Artemis II Moon Landing – Live Mission Feed",
    thumbnail: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=800&q=80",
    previewVideo: PREVIEWS[6],
    youtubeId: "jkOMpGXwDps",
    category: "Science",
    date: "2026-05-05",
    time: "4:30 AM EDT",
    views: 2100000,
    description: "Humanity returns to the Moon. Watch the live feed of the Artemis IV crewed lunar landing mission, with expert commentary from NASA engineers and astronauts. A historic milestone in human space exploration.",
  },
  {
    id: "8",
    title: "AWS re:Invent 2026 – Cloud & AI Summit",
    thumbnail: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80",
    previewVideo: PREVIEWS[7],
    youtubeId: "prVdCIHlipg",
    category: "Tech",
    date: "2026-05-08",
    time: "9:00 AM PST",
    views: 95000,
    description: "AWS re:Invent delivers the latest innovations in cloud computing, serverless, machine learning, and DevOps. Watch keynotes, deep-dive sessions, and live architecture workshops from anywhere in the world.",
  },
  {
    id: "9",
    title: "FC Barcelona vs Real Madrid – El Clásico",
    thumbnail: "https://images.unsplash.com/photo-1489944440615-453fc2b6a9a9?q=80&w=3123&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    previewVideo: PREVIEWS[8],
    youtubeId: "3j_daNHio4o",
    category: "Sports",
    date: "2026-05-10",
    time: "3:45 PM CET",
    views: 890000,
    description: "The most watched club football match on the planet. El Clásico returns with both sides fighting for La Liga supremacy. Premium multi-angle streams, tactical analysis overlay, and live player tracking.",
  },
  {
    id: "10",
    title: "Overwatch League Grand Finals 2026",
    thumbnail: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&q=80",
    previewVideo: PREVIEWS[9],
    youtubeId: "E0xzLwD9sS0",
    category: "Gaming",
    date: "2026-05-14",
    time: "5:00 PM KST",
    views: 176000,
    description: "Two elite teams battle in the Overwatch League Grand Finals for the ultimate trophy in competitive Overwatch. Watch high-frame-rate broadcasts with HeroTracker, stat overlays, and multi-POV switching.",
  },
  {
    id: "11",
    title: "Mars Rover Perseverance – Sample Return Mission Broadcast",
    thumbnail: "https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?w=800&q=80",
    previewVideo: PREVIEWS[10],
    youtubeId: "WNrTttvdIMc",
    category: "Science",
    date: "2026-05-17",
    time: "11:00 AM EDT",
    views: 760000,
    description: "Live coverage of the Mars Sample Return mission as Perseverance delivers sealed Martian rock samples. Watch scientists react in real time and discuss what these samples could reveal about life on Mars.",
  },
  {
    id: "12",
    title: "Dua Lipa – Radical Optimism Tour: Grand Finale",
    thumbnail: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800&q=80",
    previewVideo: PREVIEWS[11],
    youtubeId: "qeQfFfRy_FU",
    category: "Music",
    date: "2026-05-20",
    time: "8:30 PM BST",
    views: 305000,
    description: "The grand finale of Dua Lipa's Radical Optimism World Tour, streamed live from London. Expect stunning choreography, a full live band, and all her chart-topping hits in one unforgettable night.",
  },
  {
    id: "13",
    title: "OpenAI DevDay 2026 – GPT-6 Reveal & Live Demos",
    thumbnail: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80",
    previewVideo: PREVIEWS[12],
    youtubeId: "U9mJuUkhUzk",
    category: "Tech",
    date: "2026-05-23",
    time: "10:00 AM PDT",
    views: 430000,
    description: "OpenAI's annual developer conference goes live with the reveal of GPT-6 and next-gen API capabilities. Live coding sessions, plugin ecosystem previews, and Q&A with the OpenAI research team.",
  },
  {
    id: "14",
    title: "Wimbledon Men's Final – Centre Court Live",
    thumbnail: "https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=800&q=80",
    previewVideo: PREVIEWS[13],
    youtubeId: "I2napxp1ym0",
    category: "Sports",
    date: "2026-05-26",
    time: "1:00 PM BST",
    views: 640000,
    description: "The most prestigious match in tennis. Watch the Wimbledon Men's Singles Final live on Centre Court. HD streams with multiple angles, Hawkeye challenge replays, and expert commentary.",
  },
  {
    id: "15",
    title: "Trending Now: Top Streamers Charity Invitational",
    thumbnail: "https://images.unsplash.com/photo-1607799632518-da91dd151b38?w=800&q=80",
    previewVideo: PREVIEWS[14],
    youtubeId: "3eLJ79xEIcI",
    category: "Trending",
    date: "2026-05-30",
    time: "2:00 PM EST",
    views: 220000,
    description: "The biggest names in streaming come together for a 24-hour charity marathon. Games, challenges, music, and special guests — all in support of global digital literacy initiatives.",
  },
];

export const mockMessages = [
  { id: 1, user: "StreamKing99", text: "Let's GOOO!! 🔥🔥", color: "#22d3ee" },
  { id: 2, user: "NightOwl_X", text: "Finally it's starting!", color: "#22d3ee" },
  { id: 3, user: "ProGamer404", text: "This is insane quality stream", color: "#f97316" },
  { id: 4, user: "TechNerd_V", text: "I've been waiting weeks for this 👀", color: "#84cc16" },
  { id: 5, user: "ChillVibes", text: "Best event of the year no cap", color: "#ec4899" },
  { id: 6, user: "EpicWatcher", text: "Anyone else lag? Just me? 😅", color: "#facc15" },
  { id: 7, user: "StreamKing99", text: "Nope, buttery smooth here", color: "#22d3ee" },
  { id: 8, user: "GlitchHunter", text: "LETS GET IT 💪💪💪", color: "#60a5fa" },
  { id: 9, user: "NightOwl_X", text: "The production value is 🔥", color: "#22d3ee" },
  { id: 10, user: "RetroPixel", text: "Subbed! Worth every penny", color: "#f472b6" },
  { id: 11, user: "CodeMonkey", text: "Stream gang where you at?", color: "#34d399" },
  { id: 12, user: "TechNerd_V", text: "Right here brother!", color: "#84cc16" },
];